version: "1.0"
info:
  model: int-scaffold
packages:
- name: CustomPackageTestingProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: customPackageDef25Sept
  version: "1.0"
  gitBranch: master
- name: customPackageGit25Sept
  version: "1.0"
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: PublicPrivateCheck
  version: "1.0"
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.custompackagetesting.integrations:Copy_daf1
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: project.custompackagetesting.referencedata:ref1
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: project.custompackagetesting.integrations:child
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: project.custompackagetesting.integrations:daf1
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: project.custompackagetesting.integrations:p
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: project.custompackagetesting.integrations:ptpt
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: project.custompackagetesting.integrations:tpt
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: PublicPrivateCheck:AddPublicFlow
  packages:
  - name: PublicPrivateCheck
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1208
- serviceName: project.custompackagetesting.streaming.connections:EmbeddedMessaging
  packages:
  - name: CustomPackageTestingProject
    version: "1.0"
  - name: globalVar_var1
  - name: customPackageGit25Sept
    version: "1.0"
  - name: customPackageDef25Sept
    version: "1.0"
  - name: PublicPrivateCheck
    version: "1.0"
  - name: WmPublic
    version: 12.1.0.0.1208
